Repository OZ-Coding-School/oz_02_main-003-BE, pull requests merged in 2024-05, with the labels that each got.

#6 Feat: users api 세팅 완료 (#2)
  app/users/urls.py
  app/users/views.py
Labels: 🚀 FEAT, 👨🏻‍🍳 윤준명

#5 Feat: API 틀 작성 및 주소 수정 (#2)
  app/alerts/urls.py
  app/alerts/views.py
  app/bookmarks/urls.py
  app/bookmarks/views.py
  app/comments/urls.py
  app/comments/views.py
  app/fridges/urls.py
  app/fridges/views.py
  app/ingredients/urls.py
  app/ingredients/views.py
  app/likes/urls.py
  app/likes/views.py
  app/main/urls.py
  app/main/views.py
  app/recipes/urls.py
  app/recipes/views.py
Labels: 🚀 FEAT, 👨🏻‍🍳 강정호

#7 Feat: models create (#3)
  app/alerts/migrations/0001_initial.py
  app/alerts/models.py
  app/bookmarks/migrations/0001_initial.py
  app/bookmarks/models.py
  app/comments/migrations/0001_initial.py
  app/comments/models.py
  app/fridges/migrations/0001_initial.py
  app/fridges/models.py
  app/ingredients/migrations/0001_initial.py
  app/ingredients/models.py
  app/likes/migrations/0001_initial.py
  app/likes/models.py
  app/recipes/migrations/0001_initial.py
  app/recipes/models.py
  app/users/migrations/0001_initial.py
  app/users/models.py
Labels: 🚀 FEAT, 👨🏻‍🍳 김재섭
